language: objective-c
osx_image: xcode8
# blacklist
branches:
  except:
    - auth
before_install:
  - gem install simctl --no-rdoc --no-ri --no-document --quiet
  - ruby -rsimctl -e 'SimCtl.warmup("iPhone 7", "iOS 10.0", 300)'
script:
- set -o pipefail
- travis_retry xcodebuild -project BigBrother.xcodeproj -scheme BigBrother -sdk iphonesimulator10.0 -destination "platform=iOS Simulator,name=iPhone 7,OS=10.0" test | xcpretty -c
- pod lib lint --quick
