language: objective-c
osx_image: xcode8
# blacklist
branches:
  except:
    - auth
script:
- set -o pipefail
- xcodebuild -project BigBrother.xcodeproj -scheme BigBrother -sdk iphonesimulator10.0 -destination "platform=iOS Simulator,name=iPhone 7,OS=10.0" test | xcpretty -c
- pod lib lint --quick
